server:
  port: 9001
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/shop_demo?serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://localhost:3306/shop_demo?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka,http://localhost:8000/eureka
  instance:
    #在控制台显示服务IP
    prefer-ip-address: true #使用ip注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    #服务提供者设置服务剔除信息
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
name: servcice #向spring容器保存了一个数据常量